FROM jupyter/datascience-notebook:latest

ENV JUPYTER_ENABLE_LAB yes
ENV JUPYTER_USER       jovyan
ENV JUPYTER_PASSWORD   passwd
ENV JUPYTER_GRANT_SUDO nopass

ENV TZ                 Asia/Tokyo

USER root

RUN echo "$JUPYTER_USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$JUPYTER_USER

USER jovyan

RUN pip install jupyterlab-link-share
RUN pip install --upgrade jupyterlab jupyterlab-git

COPY entrypoint-colab.sh /entrypoint.sh

VOLUME /home/jovyan

CMD ["/entrypoint.sh"]
